

module.exports = {
  POST_RECEIVED: "POST_RECEIVED",
  UNPUBLISHED_POSTS_RECEIVED: "UNPUBLISHED_POSTS_RECEIVED",
  PUBLISHED_POSTS_RECEIVED: "PUBLISHED_POSTS_RECEIVED",
  FEED_RECEIVED: "FEED_RECEIVED",
  PROFILE_IMAGE_RECEIVED: "PROFILE_IMAGE_RECEIVED",
  MORE_POSTS_RECEIVED: "MORE_POSTS_RECEIVED"
}
